name: Build Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install just
      run: |
        sudo apt update
        sudo apt install cargo
        cargo install just
    - uses: actions/checkout@v3
    - name: Build and Run tests
      run: |
        just t
